{
  "headers": {
    "client_id": "32ed6071dbd24b6eba8ea4682e2454ce",
    "client_secret": "Bf9AeB5061Da426D9Fa90AfB758503e1",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "5e013df4-fd43-4d87-a453-6c00cee5f11b",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "137"
  },
  "clientCertificate": null,
  "method": "PUT",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/washer",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/washer",
  "listenerPath": "/api/*",
  "relativePath": "/api/washer",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/washer",
  "rawRequestPath": "/api/washer",
  "remoteAddress": "/127.0.0.1:50014",
  "requestPath": "/api/washer"
}